from abc import ABC, abstractmethod
from typing import List, Optional
from src.domain.entities.event import Event

class EventRepository(ABC):
    @abstractmethod
    def create(self, name: str, description: str | None, capacity: int) -> Event: ...
    @abstractmethod
    def get(self, event_id: int) -> Optional[Event]: ...
    @abstractmethod
    def list(self) -> List[Event]: ...
    @abstractmethod
    def update(self, event_id: int, name: str, description: str | None, capacity: int) -> Optional[Event]: ...
    @abstractmethod
    def delete(self, event_id: int) -> bool: ...