from abc import ABC, abstractmethod
from typing import List, Optional
from src.domain.entities.participant import Participant

class ParticipantRepository(ABC):
    @abstractmethod
    def create(self, name: str, email: str) -> Participant: ...
    @abstractmethod
    def get(self, participant_id: int) -> Optional[Participant]: ...
    @abstractmethod
    def get_by_email(self, email: str) -> Optional[Participant]: ...
    @abstractmethod
    def list(self) -> List[Participant]: ...
    @abstractmethod
    def update(self, participant_id: int, name: str, email: str) -> Optional[Participant]: ...
    @abstractmethod
    def delete(self, participant_id: int) -> bool: ...